spring:
  profiles:
    active: dev

mybatis:
  type-aliases-package: com.shop.pojo
  mapper-locations: classpath:mapper/*.xml
  configuration:
    auto-mapping-behavior: full
---
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shop?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
  profiles: test

---
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.93.238.102:8306/shop?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
  profiles: dev
  jackson:
    default-property-inclusion: non_null


server:
  servlet:
    context-path: /shop


